### ISSUE TITLE
ArrayIndexOutOfBoundsException processing MPEG2L3 16kHz mono 32kb

### ISSUE THREAD

**Issue by johnv-git** [Delthas/JavaMP3#5]
Input audio MPEG2L3 16kHz mono 32kb

java.lang.ArrayIndexOutOfBoundsException: 1152 at fr.delthas.javamp3.Decoder.samples_III(Decoder.java:773) ~[javamp3-1.0.1.jar:na]

com.tagtraum.ffsampledsp-complete can decode my files, but not javamp3

**Comment by delthas** [comment]
MPEG 2 Layer III is not supported yet, as stated in the README.
